name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main  # 触发部署的分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3  # 指定 Ruby 版本

      - name: Install Jekyll and dependencies
        run: |
          gem install jekyll bundler
          bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site